### PR TITLE
Add python-gpgme for checking signature of daemon installed during setup

### PR DESCRIPTION
**Pull request by patcon**
Ah, found something else that the installer recommends. It doesn't require it, but it's needlessly forgoing easy additional security without it :)

### CODE REVIEW

**Comment by peplin** [comment]
Thanks - any interest in taking over ownership of this cookbook? I actually don't use Chef to configure my desktop anymore, although I'm happy to continue to merge patches.

**Comment by patcon** [comment]
Yeah, sure thing! I expect I'm done with it, but I'd like to keep it up-to-date, so that sounds good to me. How would you like to handle this -- transfer the repo to me via settings?

**Comment by peplin** [comment]
Awesome. I'll transfer it to you via settings, but first you have to delete your fork since it will have the same name.

**Comment by patcon** [comment]
Ah gotcha. Done and done :)

**Pull request merged**
